namespace Core.Utils.Error
{
    public enum ErrorCode
    {
        None,
        Expected,
        Invalid,
        Unknown,
        InvalidFunctionArgumentsCount,
        InvalidFunctionArguments,
        UnableToExecuteFuntion,
        InvalidFunctionName,
        Missing,
        InvalidReturnType,
        RepeatedArgumnet,
        NotReturn,
        FunctionNotFound,
        UnauthorizedAccessException,
        InvalidImageContentException,
        IOException,
        UnexpectedError,
        OutOfBounds,
        ColorTypeNotDefined,
        NullReference,
        WallENotAssigned,
        ProgramNotFound,
        InvalidCastException,
        IndexOutOfRangeException,
        ExecutionCancelled,
        ExtensionError,
    }
}